version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - mynetwork

  web:
    build: .
    command: bash -c "sleep 10 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
      - ./requirements:/code/requirements
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - elasticsearch
    networks:
      - mynetwork

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - mynetwork

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    environment:
      - discovery.type=single-node
    # volumes:
    #   - ./data/elasticsearch_data:/usr/share/elasticsearch/data/nodes
    ports:
      - "9200:9200"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge


volumes:
  postgres_data:
  elasticsearch_data: